### ISSUE TITLE
Timezone_Generic crash with ArduinoLowPower and It doesn't compile

### ISSUE THREAD

**Issue by danielf3** [khoih-prog/Timezone_Generic#3]
### Describe the bug

I'm trying to compile your library with the ArduinoLowPower.h library and SigFox.h library to use it in an MKR1200 with Sigfox and it doesn't compile. It returns an error of RTCZero library (ArduinoLowPower use this library).

**Comment by khoih-prog** [comment]
Hi @danielf3 

First thanks for your interests in the [**Timezone_Generic**](https://github.com/khoih-prog/Timezone_Generic).

Please follow the requirements in the [Bug Report](https://github.com/khoih-prog/Timezone_Generic/issues/new?assignees=&labels=&template=bug_report.md&title=) and add these missing info so that anybody can duplicate the issue without losing much time to guess / assemble the code

> ### Steps to Reproduce
> 
> Steps to reproduce the behavior. Including the [MRE](https://stackoverflow.com/help/minimal-reproducible-example) sketches

Also please be noted that the library can only support SAMD21 using

1. [Currently Supported WiFi Modules and Shields](https://github.com/khoih-prog/Timezone_Generic#currently-supported-wifi-modules-and-shields)
2. [Currently Supported Ethernet Modules and Shields](https://github.com/khoih-prog/Timezone_Generic#currently-supported-ethernet-modules-and-shields)

and not the `built-in Smart RF ATA8520` used in MKR FOX 1200.
